name: Deploy to AWS and Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH for AWS
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

    - name: Deploy to AWS
      run: |
        echo "Deploying to 52.78.68.91"
        ssh -o StrictHostKeyChecking=no ec2-user@52.78.68.91 'mkdir -p ~/movie'
        rsync -avz --exclude='.git' --include='deploy.sh' --include='*/' --exclude='*' . ec2-user@52.78.68.91:~/movie/
        ssh -o StrictHostKeyChecking=no ec2-user@52.78.68.91 'cd ~/movie && ./deploy.sh'

    - name: Set up SSH for Azure
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      run: |
        echo "Deploying to 52.231.226.97"
        ssh -o StrictHostKeyChecking=no cb-user@52.231.226.97 'mkdir -p ~/movie'
        rsync -avz --exclude='.git' --include='deploy.sh' --include='*/' --exclude='*' . cb-user@52.231.226.97:~/movie/
        ssh -o StrictHostKeyChecking=no cb-user@52.231.226.97 'cd ~/movie && ./deploy.sh'
