name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      env:
        HOST_IP: ${{ secrets.HOST_IP }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "Deploying to ${HOST_IP}"
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/brandon-keypair.pem ${USERNAME}@${HOST_IP} 'mkdir -p ~/movie'
        rsync -avz --exclude='.git' -e "ssh -i ~/.ssh/brandon-keypair.pem" . ${USERNAME}@${HOST_IP}:~/movie/
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/brandon-keypair.pem ${USERNAME}@${HOST_IP} 'cd ~/movie && ./deploy.sh'
