name: Deploy to AWS and Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH for AWS
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to AWS
      env:
        AWS_HOST_IP: ${{ secrets.HOST_IP }}
        AWS_USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "Deploying to ${AWS_HOST_IP}"
        ssh -o StrictHostKeyChecking=no ${AWS_USERNAME}@${AWS_HOST_IP} 'mkdir -p ~/movie'
        rsync -avz --exclude='.git' --include='deploy.sh' --include='*/' --exclude='*' . ${AWS_USERNAME}@${AWS_HOST_IP}:~/movie/
        ssh -o StrictHostKeyChecking=no ${AWS_USERNAME}@${AWS_HOST_IP} 'cd ~/movie && ./deploy.sh'

    - name: Set up SSH for Azure
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      env:
        AZURE_HOST_IP: ${{ secrets.AZURE_HOST_IP }}
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      run: |
        echo "Deploying to ${AZURE_HOST_IP}"
        ssh -o StrictHostKeyChecking=no ${AZURE_USERNAME}@${AZURE_HOST_IP} 'mkdir -p ~/movie'
        rsync -avz --exclude='.git' --include='deploy.sh' --include='*/' --exclude='*' . ${AZURE_USERNAME}@${AZURE_HOST_IP}:~/movie/
        ssh -o StrictHostKeyChecking=no ${AZURE_USERNAME}@${AZURE_HOST_IP} 'cd ~/movie && ./deploy.sh'
